name: Deploy AKS with Terraform

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    name: 'Terraform AKS Deployment'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Extract Azure credentials
        id: extract_creds
        run: |
          echo "${{ secrets.AZURE_CREDENTIALS }}" > azure_creds.json
          echo "tenant_id=$(jq -r .tenantId azure_creds.json)" >> $GITHUB_ENV
          echo "subscription_id=$(jq -r .subscriptionId azure_creds.json)" >> $GITHUB_ENV
          echo "client_id=$(jq -r .clientId azure_creds.json)" >> $GITHUB_ENV

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: |
          terraform plan -input=false \
            -var="tenant_id=${{ env.tenant_id }}" \
            -var="subscription_id=${{ env.subscription_id }}" \
            -var="client_id=${{ env.client_id }}"

      - name: Terraform Apply
        run: |
          terraform apply -auto-approve -input=false \
            -var="tenant_id=${{ env.tenant_id }}" \
            -var="subscription_id=${{ env.subscription_id }}" \
            -var="client_id=${{ env.client_id }}"
